name: 'dev Build and deploy .apk to Firebase App Distribution '

on:
  release:
    types: [created, published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: 'true'
    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3  

      - name: Install dependencies 
        run: pnpm install --frozen-lockfile

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
        
      - name: Generate Test APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease --no-daemon
          cd ..
        shell: bash
        env:
          EXPO_NO_DOTENV: '1'
          APP_ENV: 'development'
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          API_URL: ${{ secrets.API_URL }}
      
  #    - name: Sign APK
  #     id: sign_app
  #      uses: r0adkll/sign-android-release@v1
  #      with:
  #        releaseDirectory: /home/runner/work/react-native-template-obytes/react-native-template-obytes/android/app/build/outputs/apk/debug
  #        signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
  #        alias: ${{ secrets.ANDROID_ALIAS }}
  #        keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
  #        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.ANDROID_FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: Dev
          file: /home/runner/work/react-native-template-obytess/react-native-template-obytess/android/app/build/outputs/apk/release/app-release.apk
          releaseNotes: ${{ github.event.release.name }}
